<a href="https://colab.research.google.com/github/kasim47520/Loandata-dataset/blob/main/Loan_data_code_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel('loan-data.xlsx')

In [6]:
df.head()

Unnamed: 0      id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0           2       2          2        0.0          0.0              0.0   
1           3  545583     703644     2500.0       2500.0           2500.0   
2           4  532101     687836     5000.0       5000.0           5000.0   
3           5  877788    1092507     7000.0       7000.0           7000.0   
4           6  875406    1089981     2000.0       2000.0           2000.0   

        term  int_rate  installment emp_length  ... total_acc  total_pymnt  \
0  36 months      0.00         0.00   < 1 year  ...       1.0     0.000000   
1  36 months     13.98        85.42    4 years  ...      10.0  3075.291779   
2  36 months     15.95       175.67    4 years  ...      15.0  2948.760000   
3  36 months      9.91       225.58  10+ years  ...      20.0  8082.391880   
4  36 months      5.42        60.32  10+ years  ...      15.0  2161.663244   

  total_pymnt_inv total_rec_prncp total_rec_int last_pymnt_d last_pymnt_amnt  \
0            0.00            0.00          0.00   2023-01-07            0.00   
1         3075.29         2500.00        575.29   2023-07-13           90.85   
2         2948.76         1909.02        873.81   2023-11-11          175.67   
3         8082.39         7000.00       1082.39   2023-03-14         1550.27   
4         2161.66         2000.00        161.66   2023-02-14           53.12   

  next_pymnt_d  last_credit_pull_d  repay_fail  
0   2023-01-07          2023-01-07           1  
1   2023-08-13          2023-06-16           0  
2          NaT          2023-03-12           1  
3          NaT          2023-03-14           0  
4          NaT          2023-06-16           0  

[5 rows x 37 columns]

In [7]:
df.drop(columns=['id','member_id', 'loan_amnt','funded_amnt_inv','issue_d','zip_code','addr_state','dti','delinq_2yrs','earliest_cr_line','inq_last_6mths','mths_since_last_delinq','open_acc','pub_rec','revol_bal','revol_util','total_acc','total_pymnt_inv','total_rec_int','last_pymnt_d','last_pymnt_amnt','next_pymnt_d','last_credit_pull_d'],inplace=True)

In [8]:
df

Unnamed: 0  funded_amnt       term  int_rate  installment emp_length  \
0               2          0.0  36 months      0.00         0.00   < 1 year   
1               3       2500.0  36 months     13.98        85.42    4 years   
2               4       5000.0  36 months     15.95       175.67    4 years   
3               5       7000.0  36 months      9.91       225.58  10+ years   
4               6       2000.0  36 months      5.42        60.32  10+ years   
...           ...          ...        ...       ...          ...        ...   
38475       38476       3000.0  36 months     11.99        99.63    3 years   
38476       38477      10400.0  36 months     13.49       352.88    9 years   
38477       38478      10550.0  60 months     14.96       250.77  10+ years   
38478       38479      10000.0  36 months     16.89       355.99     1 year   
38479       38480       3200.0  36 months     13.49       108.58    7 years   

      home_ownership  annual_inc verification_status  \
0               RENT         0.0        Not Verified   
1               RENT     20004.0        Not Verified   
2               RENT     59000.0        Not Verified   
3           MORTGAGE     53796.0        Not Verified   
4               RENT     30000.0        Not Verified   
...              ...         ...                 ...   
38475           RENT     74250.0            Verified   
38476           RENT     62000.0     Source Verified   
38477       MORTGAGE     95088.0     Source Verified   
38478           RENT     48720.0        Not Verified   
38479           RENT     38400.0     Source Verified   

                                             loan_status             purpose  \
0                                            Charged Off      major_purchase   
1      Does not meet the credit policy. Status:Fully ...               other   
2                                            Charged Off  debt_consolidation   
3                                             Fully Paid               other   
4                                             Fully Paid  debt_consolidation   
...                                                  ...                 ...   
38475                                         Fully Paid         credit_card   
38476                                         Fully Paid         credit_card   
38477                                         Fully Paid  debt_consolidation   
38478                                         Fully Paid  debt_consolidation   
38479                                         Fully Paid  debt_consolidation   

        total_pymnt  total_rec_prncp  repay_fail  
0          0.000000             0.00           1  
1       3075.291779          2500.00           0  
2       2948.760000          1909.02           1  
3       8082.391880          7000.00           0  
4       2161.663244          2000.00           0  
...             ...              ...         ...  
38475   3586.619764          3000.00           0  
38476  12703.534030         10400.00           0  
38477  14202.267530         10550.00           0  
38478  12815.178320         10000.00           0  
38479   3908.767275          3200.00           0  

[38480 rows x 14 columns]

In [9]:
df.isnull().sum()

Unnamed: 0               0
funded_amnt              1
term                     0
int_rate                 0
installment              1
emp_length             993
home_ownership           0
annual_inc               2
verification_status      0
loan_status              0
purpose                  0
total_pymnt              1
total_rec_prncp          1
repay_fail               0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

Unnamed: 0             0
funded_amnt            0
term                   0
int_rate               0
installment            0
emp_length             0
home_ownership         0
annual_inc             0
verification_status    0
loan_status            0
purpose                0
total_pymnt            0
total_rec_prncp        0
repay_fail             0
dtype: int64

In [12]:
df['term']=df['term'].str.replace('months','').astype(int)

In [13]:
df['funded_amnt']=df['funded_amnt'].astype(int)

In [14]:
df.term.unique()

array([36, 60])

In [15]:
backup=df.copy()

In [16]:
df.term.unique()

array([36, 60])

In [17]:
df.int_rate.unique()

array([ 0.  , 13.98, 15.95,  9.91,  5.42, 10.25,  7.49, 14.27, 23.22,
       17.27, 13.79, 15.23,  6.54, 16.63,  9.99, 21.21, 11.83, 12.53,
       13.61, 11.14,  8.9 , 15.99, 13.06, 14.17,  6.  , 16.35, 15.65,
        9.63, 11.99, 16.49,  7.29,  6.92,  6.62, 18.62, 14.62, 11.49,
       15.57,  9.88, 20.3 , 14.11, 10.59, 12.61, 18.36, 10.62, 10.75,
       12.73, 14.79, 10.37, 14.54, 10.99,  7.66, 11.71,  7.14, 17.99,
       14.72, 22.06, 12.99,  8.7 ,  8.49, 15.27, 10.46, 12.69,  6.91,
        7.9 , 13.72, 14.84, 13.12, 13.75, 20.25, 11.03, 10.74, 13.23,
       12.18, 13.99,  7.51, 13.35, 11.36, 14.26, 10.71,  9.32,  7.88,
       18.3 , 14.42,  8.59, 17.14, 12.42, 16.45,  6.03, 13.48,  8.94,
       12.98, 10.28, 18.39, 10.65, 13.22, 16.95, 14.59,  7.74, 11.89,
        7.37, 11.86, 21.36,  9.76, 14.46, 13.49, 11.12,  6.39, 14.22,
        6.17, 11.97,  6.99, 15.7 , 10.08, 18.79, 11.11, 12.72,  5.79,
       13.92, 14.38, 17.93, 17.56, 13.16, 16.32, 17.88, 21.64, 13.11,
       12.87, 13.57,

In [ ]:
df.installment.unique()

In [18]:
df.emp_length.unique()

array(['< 1 year', '4 years', '10+ years', '3 years', '5 years',
       '7 years', '2 years', '1 year', '6 years', '9 years', '8 years'],
      dtype=object)

In [19]:
emp_length_mapping={
    '< 1 year':0,
    '1 year' :1,
    '2 years':2,
    '3 years':3,
    '4 years':4,
    '5 years':5,
    '6 years':6,
    '7 years':7,
    '8 years':8,
    '9 years':9,
    '10+ years':10
}

In [20]:
df['emp_length']=df['emp_length'].replace(emp_length_mapping)

In [21]:
df.emp_length.unique()

array([ 0,  4, 10,  3,  5,  7,  2,  1,  6,  9,  8])

In [22]:
df.home_ownership.unique()

array(['RENT', 'MORTGAGE', 'OWN', 'OTHER', 'NONE'], dtype=object)

In [23]:
df['home_ownership']=df['home_ownership'].str.replace('NONE','OTHER')

In [24]:
df.home_ownership.unique()

array(['RENT', 'MORTGAGE', 'OWN', 'OTHER'], dtype=object)

In [25]:
verification_status_mapping = {
    'Not Verified':0,
    'Verified':1,
    'Source Verified':1

}

In [26]:
df['verification_status']=df['verification_status'].replace(verification_status_mapping)

In [27]:
df.loan_status.unique()

array(['Charged Off',
       'Does not meet the credit policy. Status:Fully Paid', 'Fully Paid',
       'Does not meet the credit policy. Status:Charged Off', 'Current',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Default'], dtype=object)

In [28]:
df.loan_status.value_counts()

Fully Paid                                             29266
Charged Off                                             4908
Does not meet the credit policy. Status:Fully Paid      1764
Current                                                  832
Does not meet the credit policy. Status:Charged Off      674
Late (31-120 days)                                        19
In Grace Period                                           14
Late (16-30 days)                                          7
Default                                                    1
Name: loan_status, dtype: int64

In [29]:
loan_status_mapping={
    'Does not meet the credit policy. Status:Fully Paid':'Fully Paid',
    'Does not meet the credit policy. Status:Charged Off':'Charged Off',
    'Late (31-120 days)':'Others',
    'In Grace Period':'Others',
    'Late (16-30 days)':'Others',
    'Default':'Others'

}

In [30]:
df['loan_status']=df['loan_status'].replace(loan_status_mapping)

In [31]:
df.purpose.unique()

array(['major_purchase', 'other', 'debt_consolidation', 'credit_card',
       'small_business', 'wedding', 'medical', 'car', 'home_improvement',
       'vacation', 'educational', 'house', 'moving', 'renewable_energy'],
      dtype=object)

In [32]:
df.loan_status.unique()

array(['Charged Off', 'Fully Paid', 'Current', 'Others'], dtype=object)

In [33]:
df.repay_fail.value_counts()

0    31876
1     5609
Name: repay_fail, dtype: int64

In [ ]:
df

Unnamed: 0  funded_amnt  term  int_rate  installment  emp_length  \
0               2            0    36      0.00         0.00           0   
1               3         2500    36     13.98        85.42           4   
2               4         5000    36     15.95       175.67           4   
3               5         7000    36      9.91       225.58          10   
4               6         2000    36      5.42        60.32          10   
...           ...          ...   ...       ...          ...         ...   
38475       38476         3000    36     11.99        99.63           3   
38476       38477        10400    36     13.49       352.88           9   
38477       38478        10550    60     14.96       250.77          10   
38478       38479        10000    36     16.89       355.99           1   
38479       38480         3200    36     13.49       108.58           7   

      home_ownership  annual_inc  verification_status  loan_status  \
0               RENT         0.0                    0  Charged Off   
1               RENT     20004.0                    0   Fully Paid   
2               RENT     59000.0                    0  Charged Off   
3           MORTGAGE     53796.0                    0   Fully Paid   
4               RENT     30000.0                    0   Fully Paid   
...              ...         ...                  ...          ...   
38475           RENT     74250.0                    1   Fully Paid   
38476           RENT     62000.0                    1   Fully Paid   
38477       MORTGAGE     95088.0                    1   Fully Paid   
38478           RENT     48720.0                    0   Fully Paid   
38479           RENT     38400.0                    1   Fully Paid   

                  purpose   total_pymnt  total_rec_prncp  repay_fail  
0          major_purchase      0.000000             0.00           1  
1                   other   3075.291779          2500.00           0  
2      debt_consolidation   2948.760000          1909.02           1  
3                   other   8082.391880          7000.00           0  
4      debt_consolidation   2161.663244          2000.00           0  
...                   ...           ...              ...         ...  
38475         credit_card   3586.619764          3000.00           0  
38476         credit_card  12703.534030         10400.00           0  
38477  debt_consolidation  14202.267530         10550.00           0  
38478  debt_consolidation  12815.178320         10000.00           0  
38479  debt_consolidation   3908.767275          3200.00           0  

[37485 rows x 14 columns]

In [34]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score

In [45]:
X = df.drop('repay_fail',axis=1)
y = df.repay_fail

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [47]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()


In [48]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [49]:
ohe=OneHotEncoder()
ohe.fit(X[['home_ownership','loan_status','purpose']])

OneHotEncoder()

In [50]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['home_ownership','loan_status','purpose']),
                                    remainder='passthrough')

In [51]:
clf = DecisionTreeClassifier()

In [52]:
pipe=make_pipeline(column_trans,clf)

In [53]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['MORTGAGE', 'OTHER', 'OWN', 'RENT'], dtype=object),
                                                                            array(['Charged Off', 'Current', 'Fully Paid', 'Others'], dtype=object),
                                                                            array(['car', 'credit_card', 'debt_consolidation', 'educational',
       'home_improvement', 'house', 'major_purchase', 'medical', 'moving',
       'other', 'renewable_energy', 'small_business', 'vacation',
       'wedding'], dtype=object)]),
                                                  ['home_ownership',
                                                   'loan_status',
                                                   'purpose'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [54]:
y_pred=pipe.predict(X_train)

In [55]:
r2_score(y_train,y_pred)

1.0

In [57]:
pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.4/484.4 kB 12.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.4/153.4 kB 13.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 20.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.5/17.5 MB 89.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 39.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 87.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 129.3 MB/s eta 0:

In [58]:
from pycaret.classification import setup
from pycaret.classification import compare_models

In [59]:
grid = setup(data=df, target=df.columns[-1])

In [60]:
best = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [61]:
best

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=432, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)